# Generated by Django 5.0.6 on 2024-05-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_rename_members_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
    ]
