# Generated by Django 5.0.6 on 2024-05-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_member_click_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='absent_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='late_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='present_count',
            field=models.IntegerField(default=0),
        ),
    ]
